#!/usr/bin/env bash
set -euo pipefail

if [ "$#" -ne 2 ]; then
  echo "Usage: compresser fichier.txt fichier_compresse.huff" >&2
  exit 1
fi

INPUT="$1"
OUTPUT="$2"

# 1) Compilation
make > /dev/null

JAVA_OUTPUT=$(java -cp bin compression.Main "$INPUT" "$OUTPUT")
